#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R"$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# Configures Nginx to serve a Hello World Page
echo  "Hello World!" | sudo tee /var/www/html/index.html
# Allow nginx to connect over a firewall
sudo ufw allow 'Nginx HTTP'
# Start Nginx to apply changes
sudo service nginx restart
