#!/usr/bin/env bash
# Install, configure, starts the server and also edit the default config file

sudo apt-get update -y
sudo apt-get install nginx -y

# Redirection Page
sudo sed -i '/server_name _;/a \\t location /redirect_me {\n\t\t return 301  https://www.youtube.com/watch?v=7ll7vrGHV2s;\n\t}' /etc/nginx/sites-available/default

# Reload nginx configuration
sudo service nginx restart
