#!/usr/bin/env bash
#configure a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure my Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
sudo service nginx restart
