#!/usr/bin/env bash
# 404 Not Found Page

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#creating custom header to my website
sudo sed -i "/^http {/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
# restarting my server
sudo service nginx restart
