#!/usr/bin/env bash
# Updating the package list to install HAproxy
sudo apt-get update

# Install HAProxy inside my lb server
sudo apt-get install -y haproxy

# Update HAProxy configuration file to configure it with my two servers
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 54.172.57.51:80 check
    server web-02 34.232.78.100:80 check
EOF
# start the load balancer with init
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
