#!/usr/bin/env bash
# download nginx
sudo apt-get update
sudo apt-get install nginx -y

# creating my hello world page
echo "Hello World!" | sudo tee /var/www/html/index.html
# creating a redirection to my website
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default
# creating a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
# configuring my custom page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
#creating custom header to my website
sudo sed -i "/^http {/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
# restarting my server
sudo service nginx restart
