#!/usr/bin/env bash
#my scriptthat will be used to install and configure firewall in linux

sudo apt-get -y update
sudo apt-get install -y ufw
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
