#!/usr/bin/env bash                                                             
# This my script will accept one argument whoami                                       
# Will runs the 'whoami' command under the user passed as argument
sudo -u "$1" whoami
