#!/usr/bin/env bash
# This Script is about how to connect to the server 54.160.68.207 using the users private key
# Private key is stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@54.160.68.207
